name: Terraform Plan & Policy Check

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::458108203924:role/GitHubAction_terraform_CICD_Demo
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Run tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
